# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='winCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='selectedAccount',
            field=models.ManyToManyField(blank=True, null=True, related_name='slotsWon', to='lottery.Account'),
        ),
    ]
