# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20180718_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='selectedAccount',
        ),
        migrations.AddField(
            model_name='slot',
            name='selectedAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotsWon', to='lottery.Account'),
        ),
    ]
