# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20180718_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='registeredAccounts',
            field=models.ManyToManyField(blank=True, related_name='slotsRegistered', to='lottery.Account'),
        ),
    ]
