# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20180718_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='registeredAccounts',
            new_name='entries',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='selectedAccount',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='account',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
