# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_auto_20180718_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='location',
            field=models.CharField(default='Conference Room 3A', max_length=255),
            preserve_default=False,
        ),
    ]
